config/routes.rb
Rails.application.routes.draw do


  devise_for :users, controllers: {registrations: "users/registrations",
                                   sessions: "users/sessions"}
  root "static_pages#index"

  resources :sport_tables
  resources :users, only: [:show, :index]
  resources :articles do
    resources :coments
  end
  resources :contacts, only: [:new, :index, :destroy, :create]
  resources :rooms do
    resources :chats
  end

  get "about", to: 'static_pages#about'
  get "help", to: 'static_pages#help'


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user

  validates :user_id, presence: true
  validates :title, presence: true
  validates :content, presence: true
  validates :s_content, presence: true, length: {maximum: 140}

  default_scope -> { order(created_at: :desc) }

  has_many_attached :images
  has_many :coments, dependent: :destroy
end

app/models/chat.rb
class Chat < ApplicationRecord
  belongs_to :user
  belongs_to :room

  validates :user_id, presence: true
  validates :room_id, presence: true
  validates :message, presence: true, length: {maximum: 140}
end

app/models/coment.rb
class Coment < ApplicationRecord
  belongs_to :user
  belongs_to :article

  default_scope -> { order(created_at: :desc) }

  validates :content, presence: true, length: {maximum: 140}

end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/room.rb
class Room < ApplicationRecord

  has_many :chats, dependent: :destroy

  default_scope -> { order(created_at: :desc) }

  validates :title, presence: true, length: {maximum: 140}
  validates :content, presence: true, length: {maximum: 1000}

  has_one_attached :avatar

end

app/models/sport_table.rb
class SportTable < ApplicationRecord
  belongs_to :user

  validates :user_id, presence: true

  default_scope -> { order(created_at: :desc) }

  has_many_attached :images
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :avatar
  has_many :sport_tables, dependent: :destroy
  has_many :articles
  has_many :coments, dependent: :destroy
  has_many :chats, dependent: :destroy

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  before_action :set_article, only: [:show, :edit, :destroy, :update]

  def index
    @articles = Article.paginate(page:params[:page], per_page: 5)
  end

  def new
    @article = Article.new
  end

  def create
    @article = current_user.articles.build(article_params)
    if @article.save
      redirect_to articles_path
    else
      render :new
    end
  end

  def show
    id = @article.user_id
    @user = User.find(id)
  end

  def edit
  end

  def update
    if @article.update article_params
      redirect_to articles_path
    else
      render :edit
    end
  end

  def destroy
    @article.destroy
    redirect_to articles_path
  end


  private

  def article_params
    params.require(:article).permit(:title, :content, :s_content, :category, images: [])
  end

  def set_article
    @article = Article.find(params[:id])
  end
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController

  before_action :get_room
  before_action :set_chat, only: [:show, :edit, :destroy, :update]


  def index
    @chats = @room.chats
  end

  def new
    @chat = @room.chats.build
  end

  def create
    @chat = @room.chats.build(chat_params)
    @chat.user_id = current_user.id
    if @chat.save
      redirect_to room_path(@room)
    else
      render room_path(@room)
    end
  end

  def edit
  end

  def update
    if @chat.update chat_params
      redirect_to room_path(@room)
    else
      render :edit
    end
  end

  def show
  end

  def destroy
    @chat.destroy
    redirect_to room_path(@room)
  end

  private

  def get_room
    @room = Room.find(params[:room_id])
  end

  def set_chat
    @chat = @room.chats.find(params[:id])
  end

  def chat_params
    params.require(:chat).permit(:message)
  end
end

app/controllers/coments_controller.rb
class ComentsController < ApplicationController

  before_action :get_article
  before_action :set_coment, only: [:show, :edit, :destroy, :update]

  def index
    @comments = @article.coments
  end

  def new
    @comment = @article.coments.build
  end

  def create
    @comment = @article.coments.build(post_params)
    @comment.user_id = current_user.id
    if @comment.save
      redirect_to article_path(@article)
    else
      render article_path(@article)
    end
  end

  def edit
  end

  def update
    if @comment.update post_params
      redirect_to article_path(@article)
    else
      render :edit
    end
  end

  def destroy
    @comment.destroy
    redirect_to root_path
  end

  def show
  end



  private

  def get_article
    @article = Article.find(params[:article_id])
  end

  def post_params
    params.require(:coment).permit(:content)
  end

  def set_coment
    @comment = @article.coments.find(params[:id])
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController

  before_action :set_room, only: [:show, :edit, :destroy, :update]

  def index
    @rooms = Room.all
  end

  def new
    @room = Room.new
  end

  def create
    @room = Room.new(room_params)
    if @room.save
      redirect_to rooms_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @room.update room_params
      redirect_to rooms_path
    else
      render :edit
    end
  end

  def destroy
    @room.destroy
    redirect_to rooms_path
  end

  def show
  end

  private

  def room_params
    params.require(:room).permit(:title, :content, :avatar)
  end

  def set_room
    @room = Room.find(params[:id])
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
    @rooms = Room.all
  end

  def about
  end

  def contact
  end

  def help
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @sport_results = SportTable.paginate(page:params[:page], per_page: 10)
  end

  def feed
    SportTable.where("user_id=?", id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/coments_helper.rb
module ComentsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/static_pages/about.html.erb
<% provide(:header, "About us") %>

<!-- This example requires Tailwind CSS v2.0+ -->
<div class="py-12 bg-white">
  <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
    <div class="lg:text-center">
      <h2 class="text-base text-indigo-600 font-semibold tracking-wide uppercase">Transactions</h2>
      <p class="mt-2 text-3xl leading-8 font-extrabold tracking-tight text-gray-900 sm:text-4xl">A better way to send money</p>
      <p class="mt-4 max-w-2xl text-xl text-gray-500 lg:mx-auto">Lorem ipsum dolor sit amet consect adipisicing elit. Possimus magnam voluptatum cupiditate veritatis in accusamus quisquam.</p>
    </div>

    <div class="mt-10">
      <dl class="space-y-10 md:space-y-0 md:grid md:grid-cols-2 md:gap-x-8 md:gap-y-10">
        <div class="relative">
          <dt>
            <div class="absolute flex items-center justify-center h-12 w-12 rounded-md bg-indigo-500 text-white">
              <!-- Heroicon name: outline/globe-alt -->
              <svg class="h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" aria-hidden="true">
                <path stroke-linecap="round" stroke-linejoin="round" d="M21 12a9 9 0 01-9 9m9-9a9 9 0 00-9-9m9 9H3m9 9a9 9 0 01-9-9m9 9c1.657 0 3-4.03 3-9s-1.343-9-3-9m0 18c-1.657 0-3-4.03-3-9s1.343-9 3-9m-9 9a9 9 0 019-9" />
              </svg>
            </div>
            <p class="ml-16 text-lg leading-6 font-medium text-gray-900">Competitive exchange rates</p>
          </dt>
          <dd class="mt-2 ml-16 text-base text-gray-500">Lorem ipsum, dolor sit amet consectetur adipisicing elit. Maiores impedit perferendis suscipit eaque, iste dolor cupiditate blanditiis ratione.</dd>
        </div>

        <div class="relative">
          <dt>
            <div class="absolute flex items-center justify-center h-12 w-12 rounded-md bg-indigo-500 text-white">
              <!-- Heroicon name: outline/scale -->
              <svg class="h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" aria-hidden="true">
                <path stroke-linecap="round" stroke-linejoin="round" d="M3 6l3 1m0 0l-3 9a5.002 5.002 0 006.001 0M6 7l3 9M6 7l6-2m6 2l3-1m-3 1l-3 9a5.002 5.002 0 006.001 0M18 7l3 9m-3-9l-6-2m0-2v2m0 16V5m0 16H9m3 0h3" />
              </svg>
            </div>
            <p class="ml-16 text-lg leading-6 font-medium text-gray-900">No hidden fees</p>
          </dt>
          <dd class="mt-2 ml-16 text-base text-gray-500">Lorem ipsum, dolor sit amet consectetur adipisicing elit. Maiores impedit perferendis suscipit eaque, iste dolor cupiditate blanditiis ratione.</dd>
        </div>

        <div class="relative">
          <dt>
            <div class="absolute flex items-center justify-center h-12 w-12 rounded-md bg-indigo-500 text-white">
              <!-- Heroicon name: outline/lightning-bolt -->
              <svg class="h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" aria-hidden="true">
                <path stroke-linecap="round" stroke-linejoin="round" d="M13 10V3L4 14h7v7l9-11h-7z" />
              </svg>
            </div>
            <p class="ml-16 text-lg leading-6 font-medium text-gray-900">Transfers are instant</p>
          </dt>
          <dd class="mt-2 ml-16 text-base text-gray-500">Lorem ipsum, dolor sit amet consectetur adipisicing elit. Maiores impedit perferendis suscipit eaque, iste dolor cupiditate blanditiis ratione.</dd>
        </div>

        <div class="relative">
          <dt>
            <div class="absolute flex items-center justify-center h-12 w-12 rounded-md bg-indigo-500 text-white">
              <!-- Heroicon name: outline/annotation -->
              <svg class="h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" aria-hidden="true">
                <path stroke-linecap="round" stroke-linejoin="round" d="M7 8h10M7 12h4m1 8l-4-4H5a2 2 0 01-2-2V6a2 2 0 012-2h14a2 2 0 012 2v8a2 2 0 01-2 2h-3l-4 4z" />
              </svg>
            </div>
            <p class="ml-16 text-lg leading-6 font-medium text-gray-900">Mobile notifications</p>
          </dt>
          <dd class="mt-2 ml-16 text-base text-gray-500">Lorem ipsum, dolor sit amet consectetur adipisicing elit. Maiores impedit perferendis suscipit eaque, iste dolor cupiditate blanditiis ratione.</dd>
        </div>
      </dl>
    </div>
  </div>
</div>
<% if user_signed_in? %>
<% else %>
  <div class="flex items-center -mx-4 space-x-2 overflow-x-auto overflow-y-hidden sm:justify-center flex-nowrap dark:text-gray-100">
    <%= link_to "Get started", new_user_registration_path, class: "flex items-center justify-center px-5 py-3 border border-transparent text-base font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700" %>
  </div>
<% end %>

app/views/static_pages/help.html.erb
<% provide(:header, "FAQ") %>

<section >
  <div class="container flex flex-col justify-center p-4 mx-auto md:p-8">
    <div class="flex flex-col divide-y sm:px-8 lg:px-12 xl:px-32 divide-gray-700">
      <details>
        <summary class="py-2 outline-none cursor-pointer text-lg leading-6 font-medium text-gray-900">Optio maiores eligendi molestiae totam dolores similique?</summary>
        <div class="px-4 pb-4 mt-2 text-base text-gray-500">
          <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Unde neque in fugiat magni, quas animi enim veritatis deleniti ex. Impedit.</p>
        </div>
      </details>
      <details>
        <summary class="py-2 outline-none cursor-pointer text-lg leading-6 font-medium text-gray-900">Modi dolorem veritatis culpa quos consequuntur beatae itaque excepturi perspiciatis?</summary>
        <div class="px-4 pb-4 mt-2 text-base text-gray-500">
          <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Est aspernatur quae, eos explicabo odit minima libero veniam similique quibusdam doloribus facilis ipsa accusantium vel maiores corrupti! Libero voluptate a doloribus?</p>
        </div>
      </details>
      <details>
        <summary class="py-2 outline-none cursor-pointer text-lg leading-6 font-medium text-gray-900">Magni reprehenderit possimus debitis?</summary>
        <div class="px-4 pb-4 mt-2 text-base text-gray-500">
          <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ut voluptates aspernatur dolores in consequatur doloremque inventore reprehenderit, consequuntur perspiciatis architecto.</p>
          <p>Sed consectetur quod tenetur! Voluptatibus culpa incidunt veritatis velit quasi cupiditate unde eaque! Iure, voluptatibus autem eaque unde possimus quae.</p>
        </div>
      </details>
    </div>
  </div>
</section>

app/views/static_pages/index.html.erb
<% provide(:header, "Sports community") %>

<% if user_signed_in? %>
  <%= render "rooms/index" %>
<% else %>
<p class="mt-3 text-base text-gray-500 sm:mt-5 sm:text-lg sm:max-w-xl sm:mx-auto md:mt-5 md:text-xl lg:mx-0"> The sports community is your best friend to achieve your sports goals.</p>
<p class="mt-3 text-base text-gray-500 sm:mt-5 sm:text-lg sm:max-w-xl sm:mx-auto md:mt-5 md:text-xl lg:mx-0"> Here you will find friends with similar interests. And together with them go to the heights.</p>

<div class="py-12">
  <div class="max-w-7xl mx-auto py-12 px-4 sm:px-6 lg:py-16 lg:px-8 lg:flex lg:items-center lg:justify-between">
    <h2 class="text-3xl font-extrabold tracking-tight text-gray-900 sm:text-4xl">
      <span class="block">Ready to dive in?</span>
      <span class="block text-indigo-600">Start changing your life</span>
    </h2>
    <div class="mt-8 flex lg:mt-0 lg:flex-shrink-0">
      <div class="inline-flex rounded-md shadow">
        <%= link_to "Get started", new_user_registration_path, class: "inline-flex items-center justify-center px-5 py-3 border border-transparent text-base font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700" %>
      </div>
      <div class="ml-3 inline-flex rounded-md shadow">
        <%= link_to "Learn more", about_url, class: "inline-flex items-center justify-center px-5 py-3 border border-transparent text-base font-medium rounded-md text-indigo-600 bg-white hover:bg-indigo-50" %>
      </div>
    </div>
  </div>
</div>
<% end %>