config/routes.rb
Rails.application.routes.draw do


  devise_for :users, controllers: {registrations: "users/registrations",
                                   sessions: "users/sessions"}
  root "static_pages#index"

  resources :sport_tables
  resources :users, only: [:show, :index]
  resources :articles do
    resources :coments
  end
  resources :contacts, only: [:new, :index, :destroy, :create]
  resources :rooms do
    resources :chats
  end

  get "about", to: 'static_pages#about'
  get "help", to: 'static_pages#help'


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user

  validates :user_id, presence: true
  validates :title, presence: true
  validates :content, presence: true
  validates :s_content, presence: true, length: {maximum: 140}

  default_scope -> { order(created_at: :desc) }

  has_many_attached :images
  has_many :coments, dependent: :destroy
end

app/models/chat.rb
class Chat < ApplicationRecord
  belongs_to :user
  belongs_to :room

  validates :user_id, presence: true
  validates :room_id, presence: true
  validates :message, presence: true, length: {maximum: 140}
end

app/models/coment.rb
class Coment < ApplicationRecord
  belongs_to :user
  belongs_to :article

  default_scope -> { order(created_at: :desc) }

  validates :content, presence: true, length: {maximum: 140}

end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/room.rb
class Room < ApplicationRecord

  has_many :chats, dependent: :destroy

  default_scope -> { order(created_at: :desc) }

  validates :title, presence: true, length: {maximum: 140}
  validates :content, presence: true, length: {maximum: 1000}

  has_one_attached :avatar

end

app/models/sport_table.rb
class SportTable < ApplicationRecord
  belongs_to :user

  validates :user_id, presence: true

  default_scope -> { order(created_at: :desc) }

  has_many_attached :images
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :avatar
  has_many :sport_tables, dependent: :destroy
  has_many :articles
  has_many :coments, dependent: :destroy
  has_many :chats, dependent: :destroy

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  before_action :set_article, only: [:show, :edit, :destroy, :update]

  def index
    @articles = Article.paginate(page:params[:page], per_page: 5)
  end

  def new
    @article = Article.new
  end

  def create
    @article = current_user.articles.build(article_params)
    if @article.save
      redirect_to articles_path
    else
      render :new
    end
  end

  def show
    id = @article.user_id
    @user = User.find(id)
  end

  def edit
  end

  def update
    if @article.update article_params
      redirect_to articles_path
    else
      render :edit
    end
  end

  def destroy
    @article.destroy
    redirect_to articles_path
  end


  private

  def article_params
    params.require(:article).permit(:title, :content, :s_content, :category, images: [])
  end

  def set_article
    @article = Article.find(params[:id])
  end
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController

  before_action :get_room
  before_action :set_chat, only: [:show, :edit, :destroy, :update]


  def index
    @chats = @room.chats
  end

  def new
    @chat = @room.chats.build
  end

  def create
    @chat = @room.chats.build(chat_params)
    @chat.user_id = current_user.id
    if @chat.save
      redirect_to room_path(@room)
    else
      render room_path(@room)
    end
  end

  def edit
  end

  def update
    if @chat.update chat_params
      redirect_to room_path(@room)
    else
      render :edit
    end
  end

  def show
  end

  def destroy
    @chat.destroy
    redirect_to room_path(@room)
  end

  private

  def get_room
    @room = Room.find(params[:room_id])
  end

  def set_chat
    @chat = @room.chats.find(params[:id])
  end

  def chat_params
    params.require(:chat).permit(:message)
  end
end

app/controllers/coments_controller.rb
class ComentsController < ApplicationController

  before_action :get_article
  before_action :set_coment, only: [:show, :edit, :destroy, :update]

  def index
    @comments = @article.coments
  end

  def new
    @comment = @article.coments.build
  end

  def create
    @comment = @article.coments.build(post_params)
    @comment.user_id = current_user.id
    if @comment.save
      redirect_to article_path(@article)
    else
      render article_path(@article)
    end
  end

  def edit
  end

  def update
    if @comment.update post_params
      redirect_to article_path(@article)
    else
      render :edit
    end
  end

  def destroy
    @comment.destroy
    redirect_to root_path
  end

  def show
  end



  private

  def get_article
    @article = Article.find(params[:article_id])
  end

  def post_params
    params.require(:coment).permit(:content)
  end

  def set_coment
    @comment = @article.coments.find(params[:id])
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

  before_action :correct_user, only: :index

  def index
    @contacts = Contact.all
  end

  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(contact_params)
    if @contact.save
      redirect_to root_path
    else
      render :new
    end
  end

  def destroy
    @contact = Contact.find(params[:id])
    @contact.destroy
    redirect_to root_path
  end

  private

  def contact_params
    params.require(:contact).permit(:name, :email, :message)
  end

  def correct_user
    unless user_signed_in? and current_user.workgroup == "Admin"
      redirect_to root_path
    end
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController

  before_action :set_room, only: [:show, :edit, :destroy, :update]

  def index
    @rooms = Room.all
  end

  def new
    @room = Room.new
  end

  def create
    @room = Room.new(room_params)
    if @room.save
      redirect_to rooms_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @room.update room_params
      redirect_to rooms_path
    else
      render :edit
    end
  end

  def destroy
    @room.destroy
    redirect_to rooms_path
  end

  def show
  end

  private

  def room_params
    params.require(:room).permit(:title, :content, :avatar)
  end

  def set_room
    @room = Room.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @sport_results = SportTable.paginate(page:params[:page], per_page: 10)
  end

  def feed
    SportTable.where("user_id=?", id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/coments_helper.rb
module ComentsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/_form_article.html.erb

<%= form_with model: @article do |a| %>

  <form>
    <div class="grid xl:grid-cols-2 xl:gap-6">
      <div class="relative z-0 w-full mb-6 group">
        <%= a.text_field :title, class: "block py-2.5 px-0 w-full text-sm text-gray-900 bg-transparent border-0 border-b-2 border-gray-300 appearance-none dark:text-gray dark:border-gray-600 dark:focus:border-blue-500 focus:outline-none focus:ring-0 focus:border-blue-600 peer", placeholder: " ", required: ""  %>
        <%= a.label :title, class: "peer-focus:font-medium absolute text-sm text-gray-500 dark:text-gray-400 duration-300 transform -translate-y-6 scale-75 top-3 -z-10 origin-[0] peer-focus:left-0 peer-focus:text-blue-600 peer-focus:dark:text-blue-500 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-6" %>
      </div>
      <div class="relative z-0 w-full mb-6 group">
        <%= a.text_field :category, class: "block py-2.5 px-0 w-full text-sm text-gray-900 bg-transparent border-0 border-b-2 border-gray-300 appearance-none dark:text-gray dark:border-gray-600 dark:focus:border-blue-500 focus:outline-none focus:ring-0 focus:border-blue-600 peer", placeholder: " ", required: "" %>
        <%= a.label :category, class: "peer-focus:font-medium absolute text-sm text-gray-500 dark:text-gray-400 duration-300 transform -translate-y-6 scale-75 top-3 -z-10 origin-[0] peer-focus:left-0 peer-focus:text-blue-600 peer-focus:dark:text-blue-500 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-6"  %>
      </div>
    </div>

    <div class="grid xl:grid-cols-2 xl:gap-6">
      <div class="relative z-0 w-full mb-6 group">
        <%= a.text_area :content, class: "block py-2.5 px-0 w-full text-sm text-gray-900 bg-transparent border-0 border-b-2 border-gray-300 appearance-none dark:text-gray dark:border-gray-600 dark:focus:border-blue-500 focus:outline-none focus:ring-0 focus:border-blue-600 peer", placeholder: " ", required: ""  %>
        <%= a.label :content, class: "peer-focus:font-medium absolute text-sm text-gray-500 dark:text-gray-400 duration-300 transform -translate-y-6 scale-75 top-3 -z-10 origin-[0] peer-focus:left-0 peer-focus:text-blue-600 peer-focus:dark:text-blue-500 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-6" %>
      </div>
      <div class="relative z-0 w-full mb-6 group">
        <%= a.text_area :s_content, class: "block py-2.5 px-0 w-full text-sm text-gray-900 bg-transparent border-0 border-b-2 border-gray-300 appearance-none dark:text-gray dark:border-gray-600 dark:focus:border-blue-500 focus:outline-none focus:ring-0 focus:border-blue-600 peer", placeholder: " ", required: "" %>
        <%= a.label :s_content, class: "peer-focus:font-medium absolute text-sm text-gray-500 dark:text-gray-400 duration-300 transform -translate-y-6 scale-75 top-3 -z-10 origin-[0] peer-focus:left-0 peer-focus:text-blue-600 peer-focus:dark:text-blue-500 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-6"  %>
      </div>
    </div>

    <div class="grid xl:grid-cols-2 xl:gap-6">
      <div class="relative z-0 w-full mb-6 group">
        <%= a.label :images, class: "block mb-2 text-sm font-medium text-gray-900 dark:text-gray-300"%>
        <%= a.file_field :images, multiple: true, class: "block w-full text-sm text-gray-900 border border-gray-300 rounded-lg cursor-pointer bg-gray-50 dark:text-gray-400 focus:outline-none dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400" %>
        <div class="mt-1 text-sm text-gray-500 dark:text-gray-300" id="user_avatar_help">Article picture</div>
      </div>
    </div>

    <div class="flex items-center -mx-4 px-5 space-x-2 overflow-x-auto overflow-y-hidden sm:justify-left flex-nowrap dark:text-gray-100">
      <%= a.submit "Continue", class: "flex items-center flex-shrink-0 px-5 py-2 border-b-4 dark:border-gray-800 dark:text-gray-800 hover:dark:border-blue-500 hover:dark:text-blue-500" %>
    </div>
  </form>

<% end %>

app/views/articles/edit.html.erb
<% provide(:header, "Edit Article") %>

<%= render "articles/form_article" %>

app/views/articles/index.html.erb
<% provide(:header, "Articles") %>

<div class="flex items-center -mx-4 space-x-2 overflow-x-auto overflow-y-hidden sm:justify-center flex-nowrap dark:text-gray-100">
  <% if user_signed_in?  %>
    <% if current_user.workgroup == "Admin" || "Writer" %>
      <%= link_to "New post", new_article_path, class: "flex items-center flex-shrink-0 px-5 py-2 border-b-4 dark:border-gray-800 dark:text-gray-800 hover:dark:border-blue-500 hover:dark:text-blue-500" %>
    <% end %>
  <% end %>
</div>

<section class="text-gray-600 body-font overflow-hidden">
  <div class="container px-5 py-24 mx-auto">
    <div class="-my-8 divide-y-2 divide-gray-100">
      <% @articles.each do |a| %>
        <div class="py-8 flex flex-wrap md:flex-nowrap">
        <div class="md:w-64 md:mb-0 mb-6 flex-shrink-0 flex flex-col">
          <span class="font-semibold title-font text-gray-700"><%= a.category %></span>
          <span class="mt-1 text-gray-500 text-sm"><%= a.created_at.strftime("%d %b %Y") %></span>
        </div>
        <div class="md:flex-grow">
          <h2 class="text-2xl font-medium text-gray-900 title-font mb-2"><%= a.title %></h2>
          <p class="leading-relaxed"><%= a.s_content %></p>
          <%= link_to(article_path(a), class: "text-indigo-500 inline-flex items-center mt-4") do %>
            Learn More
            <svg class="w-4 h-4 ml-2" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round">
              <path d="M5 12h14"></path>
              <path d="M12 5l7 7-7 7"></path>
            </svg>
          <% end %>
        </div>
      </div>
      <% end %>
      <div class="digg_pagination">
        <%= will_paginate @articles%>
      </div>
    </div>
  </div>
</section>

app/views/articles/new.html.erb
<% provide(:header, "New Article") %>

<%= render "articles/form_article" %>

app/views/articles/show.html.erb
<% provide(:header, @article.category) %>

<div class="flex items-center -mx-4 space-x-2 overflow-x-auto overflow-y-hidden sm:justify-center flex-nowrap dark:text-gray-100">
  <%= link_to "Back", articles_path, class: "flex items-center flex-shrink-0 px-5 py-2 border-b-4 dark:border-gray-800 dark:text-gray-800 hover:dark:border-blue-500 hover:dark:text-blue-500" %>
    <% if user_signed_in? and current_user.workgroup == "Admin" || current_user == @article.user %>
      <%= link_to "Edit", edit_article_path(@article), class: "flex items-center flex-shrink-0 px-5 py-2 border-b-4 dark:border-gray-800 dark:text-gray-800 hover:dark:border-blue-500 hover:dark:text-blue-500" %>
      <%= link_to "Delete", article_path(@article), data: { "turbo-method": :delete, turbo_confirm: "You sure?" }, class: "flex items-center flex-shrink-0 px-5 py-2 border-b-4 dark:border-gray-800 dark:text-gray-800 hover:dark:border-blue-500 hover:dark:text-blue-500" %>
  <% end %>
</div>

<article class="px-4 py-12 mx-auto max-w-7xl" >
  <div class="w-full mx-auto mb-10 text-left md:w-3/4 lg:w-1/2">
    <div class="pb-6 mb-6 border-b border-gray-200">
      <h1 class="mb-3 text-3xl font-bold text-gray-900 md:leading-tight md:text-4xl" itemprop="headline" title="Rise of Tailwind - A Utility First CSS Framework">
        <%= @article.title %>
      </h1>
      <p class="text-base text-gray-500"><%= @article.created_at.strftime("%B %d, %Y") %> — Written by <%= link_to (user_path(@user)) do %> <%= @user.name %> <%= @user.last_name %> <% end %></p>
    </div>
    <% if @article.images.attached? %>
      <% @article.images.each do |img| %>
        <%= image_tag img, class: "object-cover w-full h-64 bg-center rounded" %>
      <% end %>
    <% end %>
  </div>

  <div class="w-full mx-auto prose md:w-3/4 lg:w-1/2">
    <%= @article.content %>
  </div>
</article>

<%= render "coments/comments_block" %>

app/views/chats/_chat_block.html.erb
<link
  href="https://fonts.googleapis.com/css?family=Material+Icons|Material+Icons+Outlined|Material+Icons+Two+Tone|Material+Icons+Round|Material+Icons+Sharp"
  rel="stylesheet">


<div class="container mt-5">

  <div class="row d-flex justify-content-center">

    <div class="col-md-8">

      <% for c in @room.chats %>
        <div class="rounded-lg card p-3 mt-2 w-full mx-auto prose md:w-3/4 lg:w-1/2 bg-sky-300">

          <div class="d-flex justify-content-between align-items-center">

            <div class="user d-flex flex-row align-items-center">

              <% if User.find(c.user_id).avatar.attached? %>
                <%= image_tag User.find(c.user_id).avatar, class: "my-1 inline w-12 h-12 rounded-full py-1" %>
              <% else %>
                <img class="my-1 inline w-12 h-12 rounded-full py-1" src="https://st2.depositphotos.com/47577860/46283/v/450/depositphotos_462836132-stock-illustration-assassin-deadpool-face-icon.jpg" alt="">
              <% end %>

              <span><small class="font-weight-bold text-primary"><%= link_to (user_path(c.user_id)) do %> <%= User.find(c.user_id).name %> <%= User.find(c.user_id).last_name %> <% end %></small>
              <small><%= c.created_at.strftime("%B %d, %Y") %></small></span>

              <p class="my-1 font-weight-bold"><%= c.message %></p>
            </div>
          </div>

          <div class="action d-flex justify-content-between mt-2 align-items-center">
            <% if user_signed_in? and current_user.workgroup == "Admin" || current_user.id == c.user_id %>
              <%= link_to(edit_room_chat_path(@room, c), class: "text-black-400 hover:text-blue-800 mr-2") do %>
                <i class="material-icons-outlined text-base">edit</i>
              <% end %>
            <% end %>
          </div>
        </div>
      <% end %>

    </div>

  </div>

</div>

<% if user_signed_in?  %>
  <%= form_with(model: [@room, @room.chats.build], local: true) do |c| %>
    <div class="flex justify-center min-h-screen mt-2 w-full mx-auto prose md:w-3/4 lg:w-1/2">
      <div class="h-64  w-full rounded-[12px] ">
        <div>
          <%= c.label :add_comment, class: "text-xl font-semibold text-blue-900 cursor-pointer transition-all hover:text-black" %>
          <%= c.text_area :message, required: true, class: "h-40 px-3 text-sm py-1 mt-5 outline-none border-pink-300 w-full resize-none border rounded-lg placeholder:text-sm", placeholder: "Add your comments here" %>
        </div>
        <div class="flex justify-between mt-2">
          <%= c.submit "Add comment", class: "h-12 w-[150px] bg-blue-800 text-sm text-white rounded-lg transition-all cursor-pointer hover:bg-blue-600" %>
        </div>
      </div>
    </div>
  <% end %>
<% end %>

app/views/chats/edit.html.erb
<%= form_with(model: [@room, @chat], local: true) do |c| %>
  <div>
    <%= c.label :message %>
    <%= c.text_field :message, required: true %>
  </div>
  <%= c.submit "submit" %>
<% end %>

app/views/coments/_comments_block.html.erb
<link
  href="https://fonts.googleapis.com/css?family=Material+Icons|Material+Icons+Outlined|Material+Icons+Two+Tone|Material+Icons+Round|Material+Icons+Sharp"
  rel="stylesheet">


<div class="container mt-5">

  <div class="row d-flex justify-content-center">

    <div class="col-md-8">

      <% for coment in @article.coments %>
      <div class="rounded-lg card p-3 mt-2 w-full mx-auto prose md:w-3/4 lg:w-1/2 bg-sky-300">

        <div class="d-flex justify-content-between align-items-center">

          <div class="user d-flex flex-row align-items-center">

            <% if User.find(coment.user_id).avatar.attached? %>
              <%= image_tag User.find(coment.user_id).avatar, class: "my-1 inline w-12 h-12 rounded-full py-1" %>
            <% else %>
              <img class="my-1 inline w-12 h-12 rounded-full py-1" src="https://st2.depositphotos.com/47577860/46283/v/450/depositphotos_462836132-stock-illustration-assassin-deadpool-face-icon.jpg" alt="">
            <% end %>

            <span><small class="font-weight-bold text-primary"><%= link_to (user_path(coment.user_id)) do %> <%= User.find(coment.user_id).name %> <%= User.find(coment.user_id).last_name %> <% end %></small>
              <small><%= coment.created_at.strftime("%B %d, %Y") %></small></span>

            <p class="my-1 font-weight-bold"><%= coment.content %></p>
          </div>
        </div>

        <div class="action d-flex justify-content-between mt-2 align-items-center">
          <% if user_signed_in? and current_user.workgroup == "Admin" || current_user.id == coment.user_id %>
            <%= link_to(edit_article_coment_path(@article, coment), class: "text-black-400 hover:text-blue-800 mr-2") do %>
              <i class="material-icons-outlined text-base">edit</i>
            <% end %>
            <%= link_to([@article, coment], data: { "turbo-method": :delete,
                                           turbo_confirm: "You sure?" }, class: "text-black-400 hover:text-blue-800 mr-2") do %>
              <i class="material-icons-round text-base">delete_outline</i>
            <% end %>
          <% end %>
        </div>
      </div>
      <% end %>

    </div>

  </div>

</div>

<% if user_signed_in?  %>
  <%= form_with(model: [@article, @article.coments.build], local: true) do |c| %>
    <div class="flex justify-center min-h-screen mt-2 w-full mx-auto prose md:w-3/4 lg:w-1/2">
      <div class="h-64  w-full rounded-[12px] ">
        <div>
          <%= c.label :add_comment, class: "text-xl font-semibold text-blue-900 cursor-pointer transition-all hover:text-black" %>
          <%= c.text_area :content, required: true, class: "h-40 px-3 text-sm py-1 mt-5 outline-none border-pink-300 w-full resize-none border rounded-lg placeholder:text-sm", placeholder: "Add your comments here" %>
        </div>
        <div class="flex justify-between mt-2">
          <%= c.submit "Add comment", class: "h-12 w-[150px] bg-blue-800 text-sm text-white rounded-lg transition-all cursor-pointer hover:bg-blue-600" %>
        </div>
      </div>
    </div>
  <% end %>
<% end %>

app/views/contacts/index.html.erb
<% provide(:header, "Contact") %>

<link
  href="https://fonts.googleapis.com/css?family=Material+Icons|Material+Icons+Outlined|Material+Icons+Two+Tone|Material+Icons+Round|Material+Icons+Sharp"
  rel="stylesheet">

  <div>
    <table class="rounded-lg m-5 w-full mx-auto bg-gray-200 text-gray-800 text-center">
      <thead>
      <tr class="border-b-2 border-gray-300">
        <th class="py-3">Date</th>
        <th class="py-3">Name</th>
        <th class="py-3">Email</th>
        <th class="py-3">Message</th>
      </tr>
      </thead>
      <tbody>
      <% @contacts.each do |c| %>
        <tr class="bg-white border-b border-gray-200 ">
          <td class="py-3"><%= c.created_at.strftime("%d.%m.%Y") %></td>
          <td><%= c.name %></td>
          <td><%= c.email %></td>
          <td><%= c.message %></td>
          <td>
            <%= link_to(contact_path(c), data: { "turbo-method": :delete,
                                                     turbo_confirm: "You sure?" }, class: "text-gray-400 hover:text-blue-300 mr-2") do %>
              <i class="material-icons-round text-base">delete_outline</i>
            <% end %>
          </td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>

app/views/rooms/_index.html.erb


<div class="flex items-center -mx-4 space-x-2 overflow-x-auto overflow-y-hidden sm:justify-center flex-nowrap dark:text-gray-100">
  <% if user_signed_in? and current_user.workgroup == "Admin" %>
    <%= link_to "Add room", new_room_path, class: "flex items-center flex-shrink-0 px-5 py-2 border-b-4 dark:border-gray-800 dark:text-gray-800 hover:dark:border-blue-500 hover:dark:text-blue-500" %>
  <% end %>
</div>

<section>
  <div class="relative items-center w-full px-5 py-12 mx-auto md:px-12 lg:px-24 max-w-7xl">
    <div class="grid w-full grid-cols-1 gap-6 mx-auto lg:grid-cols-3">
      <% @rooms.each do |r| %>
      <div class="p-6">
        <% if r.avatar.attached? %>
          <%= image_tag r.avatar, class: "object-cover object-center w-full mb-8 lg:h-48 md:h-36 rounded-xl" %>
        <% else %>
          <img class="object-cover object-center w-full mb-8 lg:h-48 md:h-36 rounded-xl" src="https://vjoy.cc/wp-content/uploads/2020/10/bezymyannyjepe.jpg" alt="blog">
        <% end %>

        <h1 class="mx-auto mb-8 text-2xl font-semibold leading-none tracking-tighter text-neutral-600 lg:text-3xl"><%= r.title %></h1>

        <div class="mt-4">
          <%= link_to "Read More »", room_path(r), class: "inline-flex items-center mt-4 font-semibold text-blue-600 lg:mb-0 hover:text-neutral-600" %>
        </div>
      </div>
      <% end %>
    </div>
  </div>
</section>

app/views/rooms/edit.html.erb
<% provide(:header, "Edit room") %>

<%= render "rooms/form" %>

app/views/rooms/index.html.erb
<% provide(:header, "Forum") %>


<%= render "rooms/index" %>

app/views/rooms/new.html.erb
<% provide(:header, "New room") %>

<%= render "rooms/form" %>

app/views/rooms/show.html.erb
<% provide(:header, @room.title) %>

<div class="flex items-center -mx-4 space-x-2 overflow-x-auto overflow-y-hidden sm:justify-center flex-nowrap dark:text-gray-100">
  <%= link_to "Back", rooms_path, class: "flex items-center flex-shrink-0 px-5 py-2 border-b-4 dark:border-gray-800 dark:text-gray-800 hover:dark:border-blue-500 hover:dark:text-blue-500" %>
  <% if user_signed_in? and current_user.workgroup == "Admin" %>
    <%= link_to "Edit", edit_room_path(@room), class: "flex items-center flex-shrink-0 px-5 py-2 border-b-4 dark:border-gray-800 dark:text-gray-800 hover:dark:border-blue-500 hover:dark:text-blue-500" %>
    <%= link_to "Delete", room_path(@room), data: { "turbo-method": :delete, turbo_confirm: "You sure?" }, class: "flex items-center flex-shrink-0 px-5 py-2 border-b-4 dark:border-gray-800 dark:text-gray-800 hover:dark:border-blue-500 hover:dark:text-blue-500" %>
  <% end %>
</div>

<article class="px-4 py-12 mx-auto max-w-7xl" >


  <div class="w-full mx-auto prose md:w-3/4 lg:w-1/2">
    <%= @room.content %>
  </div>
</article>


<%= render "chats/chat_block" %>