config/routes.rb
Rails.application.routes.draw do


  devise_for :users, controllers: {registrations: "users/registrations",
                                   sessions: "users/sessions"}
  root "static_pages#index"

  resources :sport_tables
  resources :users, only: [:show, :index]
  resources :articles do
    resources :coments
  end
  resources :contacts, only: [:new, :index, :destroy, :create]
  resources :rooms do
    resources :chats
  end

  get "about", to: 'static_pages#about'
  get "help", to: 'static_pages#help'


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :avatar
  has_many :sport_tables, dependent: :destroy
  has_many :articles
  has_many :coments, dependent: :destroy
  has_many :chats, dependent: :destroy

end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :phone, :workgroup, :avatar, :last_name, :gender, :address, :birthday])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :phone, :workgroup, :avatar, :last_name, :gender, :address, :birthday])
  end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    root_path
  end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @sport_results = SportTable.paginate(page:params[:page], per_page: 10)
  end

  def feed
    SportTable.where("user_id=?", id)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_sport_results.html.erb
<link
  href="https://fonts.googleapis.com/css?family=Material+Icons|Material+Icons+Outlined|Material+Icons+Two+Tone|Material+Icons+Round|Material+Icons+Sharp"
  rel="stylesheet">

<% if @user.sport_tables.any? %>
  <div>
    <table class="rounded-lg m-5 w-full mx-auto bg-gray-200 text-gray-800 text-center">
      <thead>
      <tr class="border-b-2 border-gray-300">
        <th class="py-3">Date</th>
        <th class="py-3">Weight</th>
        <th class="py-3">Chest</th>
        <th class="py-3">Waist</th>
        <th class="py-3">Belly</th>
        <th class="py-3">Ass</th>
        <th class="py-3">Leg</th>
        <th class="py-3">Images</th>
      </tr>
      </thead>
      <tbody>
      <% @sport_results.where(user_id: @user).each do |s| %>
        <tr class="bg-white border-b border-gray-200 ">
          <td class="py-3"><%= s.created_at.strftime("%d.%m.%Y") %></td>
          <td><%= s.weight %></td>
          <td><%= s.chest %></td>
          <td><%= s.waist %></td>
          <td><%= s.belly %></td>
          <td><%= s.ass %></td>
          <td><%= s.leg %></td>
          <td><% if s.images.attached? %>
              <div class="flex flex-row-reverse justify-around -space-x-3 space-x-reverse">
                <div class="flex flex-row-reverse justify-end -space-x-3 space-x-reverse">
                  <% s.images.each do |image| %>
                    <div class="relative flex h-8 w-8 shrink-0 select-none items-center justify-center rounded-full bg-gray-100 text-sm font-bold uppercase text-gray-800 ring ring-white">
                      <%= image_tag image, class:"h-full w-full rounded-full object-cover object-center" %>
                    </div>
                  <% end %>
                </div>
              </div>
            <% end %></td>
          <td class="p-3">
            <%= link_to(sport_table_path(s), class: "text-gray-400 hover:text-blue-300 mr-2") do %>
              <i class="material-icons-outlined text-base">visibility</i>
            <% end %>
            <% if current_user == s.user %>
              <%= link_to(edit_sport_table_path(s), class: "text-gray-400 hover:text-blue-300 mr-2") do %>
                <i class="material-icons-outlined text-base">edit</i>
              <% end %>
              <%= link_to(sport_table_path(s), data: { "turbo-method": :delete,
                                                       turbo_confirm: "You sure?" }, class: "text-gray-400 hover:text-blue-300 mr-2") do %>
                <i class="material-icons-round text-base">delete_outline</i>
              <% end %>
            <% end %>
          </td>
        </tr>
      <% end %>
      </tbody>
    </table>
    <div class="digg_pagination">
      <%= will_paginate @sport_results.where(user_id: @user)%>
    </div>
  </div>
<% end %>

app/views/users/index.html.erb
<div>
  <h1 class="font-bold text-4xl">Users#index</h1>
  <p>Find me in app/views/users/index.html.erb</p>
</div>

app/views/users/show.html.erb
<% provide(:header, "Profile") %>

<!-- component -->
<style>
    :root {
        --main-color: #4a76a8;
    }

    .bg-main-color {
        background-color: var(--main-color);
    }

    .text-main-color {
        color: var(--main-color);
    }

    .border-main-color {
        border-color: var(--main-color);
    }
</style>
<link href="https://unpkg.com/tailwindcss@^1.0/dist/tailwind.min.css" rel="stylesheet">
<script src="https://cdn.jsdelivr.net/gh/alpinejs/alpine@v2.x.x/dist/alpine.min.js" defer></script>



<div class="bg-gray-100">
  <div class="container mx-auto p-5">
    <div class="md:flex no-wrap md:-mx-2 ">
      <!-- Left Side -->
      <div class="w-full md:w-3/12 md:mx-2">
        <!-- Profile Card -->
        <div class="bg-white p-3 border-t-4 border-green-400">
          <div class="image overflow-hidden">
            <% if @user.avatar.attached? %>
              <%= image_tag @user.avatar, class: "h-auto w-full mx-auto" %>
            <% else %>
              <img class="h-auto w-full mx-auto"
                   src="https://st2.depositphotos.com/47577860/46283/v/450/depositphotos_462836132-stock-illustration-assassin-deadpool-face-icon.jpg"
                   alt="">
            <% end %>
          </div>
          <h1 class="text-gray-900 font-bold text-xl leading-8 my-1"><%= @user.name %> <%= @user.last_name %></h1>
          <h3 class="text-gray-600 font-lg text-semibold leading-6">Owner at Her Company Inc.</h3>
          <!--<p class="text-sm text-gray-500 hover:text-gray-600 leading-6">Lorem ipsum dolor sit amet
            consectetur adipisicing elit.
            Reprehenderit, eligendi dolorum sequi illum qui unde aspernatur non deserunt</p>-->
          <ul
            class="bg-gray-100 text-gray-600 hover:text-gray-700 hover:shadow py-2 px-3 mt-3 divide-y rounded shadow-sm">
            <li class="flex items-center py-3">
              <span>Status</span>
              <% if @user.workgroup == "Admin" %>
              <span class="ml-auto"><span
                class="bg-red-500 py-1 px-2 rounded text-white text-sm"><%= @user.workgroup %></span>
              <% elsif @user.workgroup == "Writer" %>
              <span class="ml-auto"><span
                class="bg-yellow-500 py-1 px-2 rounded text-white text-sm"><%= @user.workgroup %></span>
              <% else %>
                <span class="ml-auto"><span
                  class="bg-green-500 py-1 px-2 rounded text-white text-sm">User</span>
              <% end %>
              </span>
            </li>
          </ul>
        </div>
        <!-- End of profile card -->
        <div class="my-4"></div>

      </div>
      <!-- Right Side -->
      <div class="w-full md:w-9/12 mx-2 h-64">
        <!-- Profile tab -->
        <!-- About Section -->
        <div class="bg-white p-3 shadow-sm rounded-sm">
          <div class="flex items-center space-x-2 font-semibold text-gray-900 leading-8">
                        <span clas="text-green-500">
                            <svg class="h-5" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24"
                                 stroke="currentColor">
                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                      d="M16 7a4 4 0 11-8 0 4 4 0 018 0zM12 14a7 7 0 00-7 7h14a7 7 0 00-7-7z" />
                            </svg>
                        </span>
            <span class="tracking-wide">About</span>
          </div>
          <div class="text-gray-700">
            <div class="grid md:grid-cols-2 text-sm">
              <div class="grid grid-cols-2">
                <div class="px-4 py-2 font-semibold">First Name</div>
                <div class="px-4 py-2"><%= @user.name %></div>
              </div>
              <div class="grid grid-cols-2">
                <div class="px-4 py-2 font-semibold">Last Name</div>
                <div class="px-4 py-2"><%= @user.last_name %></div>
              </div>
              <div class="grid grid-cols-2">
                <div class="px-4 py-2 font-semibold">Gender</div>
                <div class="px-4 py-2"><%= @user.gender %></div>
              </div>
              <div class="grid grid-cols-2">
                <div class="px-4 py-2 font-semibold">Contact No.</div>
                <div class="px-4 py-2"><%= @user.phone %></div>
              </div>
              <div class="grid grid-cols-2">
                <div class="px-4 py-2 font-semibold">Address</div>
                <div class="px-4 py-2"><%= @user.address %></div>
              </div>
              <div class="grid grid-cols-2">
                <div class="px-4 py-2 font-semibold">Email.</div>
                <div class="px-4 py-2"><%= @user.email %></div>
              </div>
              <div class="grid grid-cols-2">
                <div class="px-4 py-2 font-semibold">Birthday</div>
                <div class="px-4 py-2"><%= @user.birthday %></div>
              </div>
            </div>
          </div>
        </div>
        <!-- End of about section -->

        <div class="my-4"></div>

        <!-- Experience and education -->
        <div class="bg-white p-3 shadow-sm rounded-sm">
          <% if current_user.present? && current_user.id ==  @user.id %>
          <%= link_to "Add results", new_sport_table_path, class: "group relative w-3/12 flex justify-center py-2 px-4 border border-transparent text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500" %>
          <% end %>
          <%= render "users/sport_results" %>
        </div>

        <!-- End of profile tab -->
      </div>
    </div>
  </div>
</div>