config/routes.rb
Rails.application.routes.draw do


  devise_for :users, controllers: {registrations: "users/registrations",
                                   sessions: "users/sessions"}
  root "static_pages#index"

  resources :sport_tables
  resources :users, only: [:show, :index]
  resources :articles do
    resources :coments
  end
  resources :contacts, only: [:new, :index, :destroy, :create]
  resources :rooms do
    resources :chats
  end

  get "about", to: 'static_pages#about'
  get "help", to: 'static_pages#help'


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user

  validates :user_id, presence: true
  validates :title, presence: true
  validates :content, presence: true
  validates :s_content, presence: true, length: {maximum: 140}

  default_scope -> { order(created_at: :desc) }

  has_many_attached :images
  has_many :coments, dependent: :destroy
end

app/models/chat.rb
class Chat < ApplicationRecord
  belongs_to :user
  belongs_to :room

  validates :user_id, presence: true
  validates :room_id, presence: true
  validates :message, presence: true, length: {maximum: 140}
end

app/models/coment.rb
class Coment < ApplicationRecord
  belongs_to :user
  belongs_to :article

  default_scope -> { order(created_at: :desc) }

  validates :content, presence: true, length: {maximum: 140}

end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/room.rb
class Room < ApplicationRecord

  has_many :chats, dependent: :destroy

  default_scope -> { order(created_at: :desc) }

  validates :title, presence: true, length: {maximum: 140}
  validates :content, presence: true, length: {maximum: 1000}

  has_one_attached :avatar

end

app/models/sport_table.rb
class SportTable < ApplicationRecord
  belongs_to :user

  validates :user_id, presence: true

  default_scope -> { order(created_at: :desc) }

  has_many_attached :images
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :avatar
  has_many :sport_tables, dependent: :destroy
  has_many :articles
  has_many :coments, dependent: :destroy
  has_many :chats, dependent: :destroy

end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController

  before_action :get_room
  before_action :set_chat, only: [:show, :edit, :destroy, :update]


  def index
    @chats = @room.chats
  end

  def new
    @chat = @room.chats.build
  end

  def create
    @chat = @room.chats.build(chat_params)
    @chat.user_id = current_user.id
    if @chat.save
      redirect_to room_path(@room)
    else
      render room_path(@room)
    end
  end

  def edit
  end

  def update
    if @chat.update chat_params
      redirect_to room_path(@room)
    else
      render :edit
    end
  end

  def show
  end

  def destroy
    @chat.destroy
    redirect_to room_path(@room)
  end

  private

  def get_room
    @room = Room.find(params[:room_id])
  end

  def set_chat
    @chat = @room.chats.find(params[:id])
  end

  def chat_params
    params.require(:chat).permit(:message)
  end
end

app/controllers/coments_controller.rb
class ComentsController < ApplicationController

  before_action :get_article
  before_action :set_coment, only: [:show, :edit, :destroy, :update]

  def index
    @comments = @article.coments
  end

  def new
    @comment = @article.coments.build
  end

  def create
    @comment = @article.coments.build(post_params)
    @comment.user_id = current_user.id
    if @comment.save
      redirect_to article_path(@article)
    else
      render article_path(@article)
    end
  end

  def edit
  end

  def update
    if @comment.update post_params
      redirect_to article_path(@article)
    else
      render :edit
    end
  end

  def destroy
    @comment.destroy
    redirect_to root_path
  end

  def show
  end



  private

  def get_article
    @article = Article.find(params[:article_id])
  end

  def post_params
    params.require(:coment).permit(:content)
  end

  def set_coment
    @comment = @article.coments.find(params[:id])
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController

  before_action :set_room, only: [:show, :edit, :destroy, :update]

  def index
    @rooms = Room.all
  end

  def new
    @room = Room.new
  end

  def create
    @room = Room.new(room_params)
    if @room.save
      redirect_to rooms_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @room.update room_params
      redirect_to rooms_path
    else
      render :edit
    end
  end

  def destroy
    @room.destroy
    redirect_to rooms_path
  end

  def show
  end

  private

  def room_params
    params.require(:room).permit(:title, :content, :avatar)
  end

  def set_room
    @room = Room.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @sport_results = SportTable.paginate(page:params[:page], per_page: 10)
  end

  def feed
    SportTable.where("user_id=?", id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/coments_helper.rb
module ComentsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb


<div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
  <div class="flex items-center justify-between h-16">
    <div class="flex items-center">
      <div class="flex-shrink-0">
        <a href="/">
          <img class="h-8 w-8" src="https://papik.pro/uploads/posts/2021-11/1636182602_6-papik-pro-p-sportivnie-logotipi-foto-7.png" alt="Workflow">
        </a>
      </div>
      <div class="hidden md:block">
        <div class="ml-10 flex items-baseline space-x-4">
          <!-- Current: "bg-gray-900 text-white", Default: "text-gray-300 hover:bg-gray-700 hover:text-white" -->
          <%= link_to "Home", root_path, class: "text-gray-300 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium" %>

          <%= link_to "Articles", articles_path, class: "text-gray-300 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium" %>

          <%= link_to "Forum", rooms_path, class: "text-gray-300 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium" %>

          <%= link_to "About", about_path, class: "text-gray-300 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium" %>

          <% if user_signed_in? and current_user.workgroup == "Admin" %>
          <%= link_to "Contact", contacts_path, class: "text-gray-300 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium" %>
          <% else%>

            <%= link_to "Contact", new_contact_path, class: "text-gray-300 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium" %>
          <% end %>
          <%= link_to "Help", help_path, class: "text-gray-300 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium" %>
        </div>
      </div>
    </div>
    <div class="hidden md:block">
      <div class="ml-4 flex items-center md:ml-6">

        <!-- Profile dropdown -->
        <script src="https://cdn.jsdelivr.net/gh/alpinejs/alpine@v2.x.x/dist/alpine.min.js" defer></script>
        <nav :class="{'flex': open, 'hidden': !open}"
             class="flex-col flex-grow pb-4 md:pb-0 hidden md:flex md:justify-end md:flex-row">
          <div @click.away="open = false" class="relative" x-data="{ open: false }">
            <% if user_signed_in?  %>
            <button @click="open = !open"
                    class="flex flex-row items-center space-x-2 w-full px-4 py-2 mt-2 text-sm font-semibold text-left bg-transparent md:w-auto md:inline md:mt-0 md:ml-4">
              <span class= "text-gray-300 rounded-md text-sm font-medium"><%= current_user.name %> <%= current_user.last_name %></span>
              <% if current_user.avatar.attached? %>
                <%= image_tag current_user.avatar, class: "inline w-8 h-8 rounded-full" %>
              <% else %>
                <img class="inline h-8 w-8 rounded-full" src="https://st2.depositphotos.com/47577860/46283/v/450/depositphotos_462836132-stock-illustration-assassin-deadpool-face-icon.jpg" alt="">
              <% end %>
            <% else %>
              <%= link_to "Sing in", new_user_session_path, class: "text-gray-300 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium"%>
              <%= link_to "Sing up", new_user_registration_path, class: "text-gray-300 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium"%>
            <% end %>
            </button>
            <div x-show="open" x-transition:enter="transition ease-out duration-100"
                 x-transition:enter-start="transform opacity-0 scale-95"
                 x-transition:enter-end="transform opacity-100 scale-100"
                 x-transition:leave="transition ease-in duration-75"
                 x-transition:leave-start="transform opacity-100 scale-100"
                 x-transition:leave-end="transform opacity-0 scale-95"
                 class="absolute right-0 w-full mt-2 origin-top-right rounded-md shadow-lg md:w-48">
              <div class="origin-top-right absolute right-0 mt-2 w-48 rounded-md shadow-lg py-1 bg-white ring-1 ring-black ring-opacity-5 focus:outline-none" role="menu" aria-orientation="vertical" aria-labelledby="user-menu-button" tabindex="-1">
                <%= link_to "Your Profile", current_user, class: "block px-4 py-2 text-sm text-gray-700" %>
                <%= link_to "Settings", edit_user_registration_path, class: "block px-4 py-2 text-sm text-gray-700" %>
                <div class="border-b"></div>
                <%= link_to "Sign out", destroy_user_session_path, data: {"turbo-method": :delete}, class: "block px-4 py-2 text-sm text-gray-700" %>
              </div>
            </div>
          </div>
        </nav>
      </div>
    </div>
    <div class="-mr-2 flex md:hidden">
      <!-- Mobile menu button -->
      <button type="button" class="bg-gray-800 inline-flex items-center justify-center p-2 rounded-md text-gray-400 hover:text-white hover:bg-gray-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-offset-gray-800 focus:ring-white" aria-controls="mobile-menu" aria-expanded="false">
        <span class="sr-only">Open main menu</span>
        <!--
          Heroicon name: outline/menu

          Menu open: "hidden", Menu closed: "block"
        -->
        <svg class="block h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" aria-hidden="true">
          <path stroke-linecap="round" stroke-linejoin="round" d="M4 6h16M4 12h16M4 18h16" />
        </svg>
        <!--
          Heroicon name: outline/x

          Menu open: "block", Menu closed: "hidden"
        -->
        <svg class="hidden h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" aria-hidden="true">
          <path stroke-linecap="round" stroke-linejoin="round" d="M6 18L18 6M6 6l12 12" />
        </svg>
      </button>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Test0606</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>

  <div class="min-h-full">
    <nav class="bg-gray-800">
      <%= render "layouts/header" %>

      <!-- Mobile menu, show/hide based on menu state. -->
      <div class="md:hidden" id="mobile-menu">
        <div class="px-2 pt-2 pb-3 space-y-1 sm:px-3">
          <!-- Current: "bg-gray-900 text-white", Default: "text-gray-300 hover:bg-gray-700 hover:text-white" -->
          <a href="#" class="bg-gray-900 text-white block px-3 py-2 rounded-md text-base font-medium" aria-current="page">Dashboard</a>

          <a href="#" class="text-gray-300 hover:bg-gray-700 hover:text-white block px-3 py-2 rounded-md text-base font-medium">Team</a>

          <a href="#" class="text-gray-300 hover:bg-gray-700 hover:text-white block px-3 py-2 rounded-md text-base font-medium">Projects</a>

          <a href="#" class="text-gray-300 hover:bg-gray-700 hover:text-white block px-3 py-2 rounded-md text-base font-medium">Calendar</a>

          <a href="#" class="text-gray-300 hover:bg-gray-700 hover:text-white block px-3 py-2 rounded-md text-base font-medium">Reports</a>
        </div>
        <div class="pt-4 pb-3 border-t border-gray-700">
          <div class="flex items-center px-5">
            <div class="flex-shrink-0">
              <img class="h-10 w-10 rounded-full" src="https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80" alt="">
            </div>
            <div class="ml-3">
              <div class="text-base font-medium leading-none text-white">Tom Cook</div>
              <div class="text-sm font-medium leading-none text-gray-400">tom@example.com</div>
            </div>
            <button type="button" class="ml-auto bg-gray-800 flex-shrink-0 p-1 rounded-full text-gray-400 hover:text-white focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-offset-gray-800 focus:ring-white">
              <span class="sr-only">View notifications</span>
              <!-- Heroicon name: outline/bell -->
              <svg class="h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" aria-hidden="true">
                <path stroke-linecap="round" stroke-linejoin="round" d="M15 17h5l-1.405-1.405A2.032 2.032 0 0118 14.158V11a6.002 6.002 0 00-4-5.659V5a2 2 0 10-4 0v.341C7.67 6.165 6 8.388 6 11v3.159c0 .538-.214 1.055-.595 1.436L4 17h5m6 0v1a3 3 0 11-6 0v-1m6 0H9" />
              </svg>
            </button>
          </div>
          <div class="mt-3 px-2 space-y-1">
            <a href="#" class="block px-3 py-2 rounded-md text-base font-medium text-gray-400 hover:text-white hover:bg-gray-700">Your Profile</a>

            <a href="#" class="block px-3 py-2 rounded-md text-base font-medium text-gray-400 hover:text-white hover:bg-gray-700">Settings</a>

            <a href="#" class="block px-3 py-2 rounded-md text-base font-medium text-gray-400 hover:text-white hover:bg-gray-700">Sign out</a>
          </div>
        </div>
      </div>
    </nav>

    <header class="bg-white shadow">
      <div class="max-w-7xl mx-auto py-6 px-4 sm:px-6 lg:px-8">
        <h1 class="text-3xl font-bold text-gray-900"><%= yield(:header) %></h1>
      </div>
    </header>
    <main>
      <div class="max-w-7xl mx-auto py-6 sm:px-6 lg:px-8">
        <%= yield %>
      </div>
    </main>
  </div>




  </body>
</html>